## Importing the Packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True, precision = 2, linewidth=100) # Just formart the printout to screen for better viewing

## Importing the Data

In [3]:
original_data = np.genfromtxt("loan-data.csv", delimiter = ';', 
                              skip_header = 1,
                              autostrip = True,
                             )
original_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [4]:
np.isnan(original_data).sum() # number of missing values in the data set

88005

In [5]:
temp_max_fill = np.nanmax(original_data) + 1
temp_mean = np.nanmean(original_data, axis = 0) # Calculate the means of nan(null) values per column
temp_mean

<ipython-input-5-f6dfa610a683>:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(original_data, axis = 0) # Calculate the means of nan(null) values per column


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [6]:
temp_stats = np.array([np.nanmin(original_data, axis = 0),
                      temp_mean,
                      np.nanmax(original_data, axis = 0)])

<ipython-input-6-86da27e04166>:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(original_data, axis = 0),
<ipython-input-6-86da27e04166>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(original_data, axis = 0)])


In [7]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [8]:
columns_string = np.argwhere(np.isnan(temp_mean)).squeeze() # Get the index of the columns which contain string values (.i.e columns with means data nan)
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
columns_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze() # Get the index of the columns which do not contain string values (.i.e columns with means data False)
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [10]:
original_data_strings = np.genfromtxt("loan-data.csv",
                             delimiter = ';', 
                             skip_header = 1,
                             autostrip = True,
                             usecols=columns_string,
                             dtype = np.str)# We reimport the data but this time we only use the columns with string datatypes
original_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
original_data_numeric = np.genfromtxt("loan-data.csv",
                             delimiter = ';', 
                             skip_header = 1,
                             autostrip = True,
                             usecols=columns_numeric,
                             filling_values = temp_max_fill)# We reimport the data but this time we only use the columns with numeric datatypes
original_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [12]:
original_data_headers = np.genfromtxt("loan-data.csv",
                             delimiter = ';', 
                             skip_footer= original_data.shape[0], # we skip the number of rows at the end of the line                            
                             autostrip = True,                             
                             dtype = np.str)# We reimport the data but this time we only import the header

In [13]:
# Split the original_data_headers into two, i.e one for strings and the other for numeric
# Since we already have columns_strings and columns_numeric which contain the indexes of the string and numeric columns
# We can just slice the original_data_headers into those two

header_string, header_numeric = original_data_headers[columns_string], original_data_headers[columns_numeric],

In [14]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [15]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [16]:
# We create a checkpoint to save the progress of the work.
# This takes a filename, a header and a data source and save as a .npz file

def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [17]:
checkpoint_test = checkpoint("checkpoint-test", header_string, original_data_strings)

In [18]:
# checkpoint_test['header']  # print out the header of the current checkpoint file
checkpoint_test['data'] # print out the data of the current checkpoint file

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [19]:
# Test if the data is equal to the checkpoint_test['data']
np.array_equal(checkpoint_test['data'], original_data_strings)

True

## Manipulating String Columns

In [20]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
header_string[0] = 'issued_date'

In [22]:
header_string

array(['issued_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue Date

In [23]:
original_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [24]:
# Working with Dates: convert date months to int
original_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [25]:
# Get unique values of the Date fields
np.unique(original_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [26]:
# From observation it seems every date is in the year 2015 so stripping 15 off the date won't cause a problem
np.chararray.strip(original_data_strings[:,0], '-15')

chararray(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [27]:
original_data_strings[:,0] = np.chararray.strip(original_data_strings[:,0], '-15')
original_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [28]:
# We arrange the months in ascending order in an array 
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [29]:
# We use a range of 13 i.e from o - 12 to assign int values to every month and 0 to empty months
for i in range(13):
        original_data_strings[:,0] = np.where(original_data_strings[:,0] == months[i],
                                          i,
                                          original_data_strings[:,0])

In [30]:
original_data_strings[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

### Loan Status

In [31]:
original_data_strings

array([['5', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [32]:
original_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [33]:
np.unique(original_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [34]:
len(np.unique(original_data_strings[:,1])) # So we have 9 distinct values with '', being part of them. so we can assign in to thies values

9

In [35]:
# Create an array containing on ly the distinct values so we can loop through
loan_status = np.unique(original_data_strings[:,1])
loan_status

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [36]:
for i in loan_status:
    print(i)


Charged Off
Current
Default
Fully Paid
In Grace Period
Issued
Late (16-30 days)
Late (31-120 days)


In [37]:
# We have been told that loan status is just good or bad so there is a category of status that are goood and others are bad
bad_status = np.array(['','Charged Off','Default','Late (31-120 days)'])
bad_status

# since we know bas loan statuses, we can only confirm that the rest are good

array(['', 'Charged Off', 'Default', 'Late (31-120 days)'], dtype='<U18')

In [38]:
# We will assign 0 to bad loan statuses and 1 to good loan status
original_data_strings[:,1] = np.where(np.isin(original_data_strings[:,1], bad_status), # if bad_status is in original_data_strings[:,1]
                                     0, # substitute it with 0 else substitute it with 1
                                     1) # Where original_data_strings[:,1] is equal to bad loan status, assign 0 else assign 1

original_data_strings[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

In [39]:
np.unique(original_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [40]:
# for i in range(9):
#     original_data_strings[:,1] = np.where(original_data_strings[:,1] == loan_status[i],
#                                          i,
#                                          original_data_strings[:,1])
# original_data_strings[:,1]

### Term

In [41]:
original_data_strings

array([['5', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [42]:
original_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [43]:
np.unique(original_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [44]:
original_data_strings[:,2] = np.chararray.strip(original_data_strings[:,2], " months")

In [45]:
original_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [46]:
# We change the name term to something more explicit
header_string[2] = 'term_months'
header_string

array(['issued_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [47]:
# From the instructions, we are asked to assign the value of 60 to all missing terms(now term_months)

np.unique(original_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [48]:
# np.unique(np.where(original_data_strings[:,2]=='','60',original_data_strings[:,2])) # Test if assignment works without modifying the column
original_data_strings[:,2] = np.where(original_data_strings[:,2]=='','60',original_data_strings[:,2])# if original_data_strings[:,2] == '',
                                                                     # fill it with '60', else maintain the actual value
original_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [49]:
np.unique(original_data_strings[:,2]) # Test Results

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [50]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [51]:
np.unique(original_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [52]:
np.unique(original_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [53]:
# Here since grade and sub_grade differe's by the 

#### Filling Sub Grade

In [54]:
for i in np.unique(original_data_strings[:,3])[1:]:
    original_data_strings[:,4] = np.where((original_data_strings[:,4] == '') & (original_data_strings[:,3] == i),
                                      i + '5',
                                      original_data_strings[:,4])
original_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [55]:
np.unique(original_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [56]:
np.unique(original_data_strings[:,4], return_counts = True) # We check howmany times each unique value appears 
# The first array gives the values and the second array gives the number of times it appears in the unique array

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [57]:
# Since we don't want to loose values, and for any withheld information, we assume the worst.
# Our manager has instruct us to use the lowest possible grade which is H1, 
# so have to replace all empty sub_grade values with H1

# np.unique(np.where(original_data_strings[:,4]=='', 'H1', original_data_strings[:,4])) #testing
original_data_strings[:,4] = np.where(original_data_strings[:,4]=='', 'H1', original_data_strings[:,4])

In [58]:
np.unique(original_data_strings[:,4], return_counts = True) # No more '' values

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

#### Removing Grade

In [59]:
# Since sub_grade better explains grades, we can safely remove grades

In [60]:
# deleting grade column data
original_data_strings = np.delete(original_data_strings, 3, axis = 1)# array to delete from, index, axis

In [61]:
original_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [62]:
header_string[3]

'grade'

In [63]:
# deleting grade column header
header_string = np.delete(header_string, 3)# array to delete from, no axis here

In [64]:
header_string[3]

'sub_grade'

#### Converting Sub Grade

In [65]:
np.unique(original_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [66]:
keys = list(np.unique(original_data_strings[:,3]))                         
values = list(range(1, np.unique(original_data_strings[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [67]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [68]:
for i in np.unique(original_data_strings[:,3]):
        original_data_strings[:,3] = np.where(original_data_strings[:,3] == i, 
                                          dict_sub_grade[i],
                                          original_data_strings[:,3])

In [69]:
original_data_strings[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

### Verification Status

In [70]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [71]:
np.unique(original_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [72]:
# for all verification data, if data is 'Not Verified', we assign a 0 else 1
original_data_strings[:,4] = np.where((original_data_strings[:,4] == '') | (original_data_strings[:,4] == 'Not Verified'), 0, 1)

In [73]:
np.unique(original_data_strings[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [74]:
original_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [75]:
np.unique(original_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [76]:
# Striping the the url column off its string
np.chararray.strip(original_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=") # Test

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [77]:
original_data_strings[:,5] = np.chararray.strip(original_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [78]:
# From observation, it seems the id column is same as the id in the url
original_data_headers

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [79]:
# Trying to remove quotation marks to better visualise if data is same as that of url___id
original_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [80]:
# Intuition seems to be queit so, the ids are same
original_data_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [81]:
# To confirm our intuition, we use the array_equal method to confirm if the two arrays are equal
np.array_equal(original_data_numeric[:,0].astype(dtype = np.int32), original_data_strings[:,5].astype(dtype = np.int32))

True

In [82]:
# Since the only difference in url is the Id section and this can be gotten anytime from the column Id,
# there's no need to keep this column (URL) so we might as well delete it

original_data_strings = np.delete(original_data_strings, 5, axis = 1)
header_string = np.delete(header_string, 5)

In [83]:
original_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [84]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [85]:
original_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [86]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### State Address

In [87]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [88]:
# Change the name from just state to a more comprehensive name state_address
header_string[5] = "state_address"

In [89]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [90]:
states_names, states_count = np.unique(original_data_strings[:,5], return_counts = True) # Get a unique count of number ofstate appearnce
states_count_sorted = np.argsort(-states_count) # Sort the unique states in Ascendinding order
states_names[states_count_sorted], states_count[states_count_sorted] # Get correnponding sorted names and counts of states

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [103]:
original_data_strings[:,5] = np.where(original_data_strings[:,5] == '', 
                                  0, 
                                  original_data_strings[:,5])

In [104]:
# Classify and divide the states by US Geographic Regions
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [105]:
# Assign the values 1,2,3, or 4 to states depending on their US Geographic Regions
original_data_strings[:,5] = np.where(np.isin(original_data_strings[:,5], states_west), 1, original_data_strings[:,5])
original_data_strings[:,5] = np.where(np.isin(original_data_strings[:,5], states_south), 2, original_data_strings[:,5])
original_data_strings[:,5] = np.where(np.isin(original_data_strings[:,5], states_midwest), 3, original_data_strings[:,5])
original_data_strings[:,5] = np.where(np.isin(original_data_strings[:,5], states_east), 4, original_data_strings[:,5])

In [106]:
np.unique(original_data_strings[:,5]) # All states now belong to a given US Geographic Regions

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [107]:
original_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [109]:
# original_data_strings.astype(np.int)

np.unique(original_data_strings, return_counts=True)

(array(['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
        '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
        '4', '5', '6', '60', '7', '8', '9'], dtype='<U69'),
 array([ 4860, 19662,  1728,  1476,  1564,   586,   564,   577,   391,   267,   250,   255,  4192,
          288,   235,   162,   171,   139,   160,    94,    52,    34,    43,  2531,    24,    19,
           10,     3,     7,     5,  6290,  2996,  1333,  1163,  3719,  1578,  1376,  1196],
       dtype=int64))

In [112]:
# All original_data_strings now contains int values and 
# since our main Goal thus far was to convert them to numeric data, we can as well cast them to integers

original_data_strings.astype(np.int) # Test

original_data_strings = original_data_strings.astype(np.int)

In [113]:
original_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [114]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_string, original_data_strings)

In [115]:
checkpoint_strings["header"]

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [116]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [118]:
np.array_equal(checkpoint_strings['data'], original_data_strings)

True

## Manipulating Numeric Columns

In [119]:
original_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [120]:
np.isnan(original_data_numeric).sum()

0

### Substitute "Filler" Values

In [121]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [122]:
temp_max_fill

68616520.0

In [123]:
np.isin(original_data_numeric[:,0], temp_max_fill)

array([False, False, False, ..., False, False, False])

In [124]:
np.isin(original_data_numeric[:,0], temp_max_fill).sum()

0

In [125]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

In [127]:
temp_stats[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [128]:
original_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [129]:
# We replace all the previously empty funded amount with the minimum possible value since it is empty
original_data_numeric[:,2] = np.where(original_data_numeric[:,2] == temp_max_fill, # if value at original_data_numeric[:,2] is same as max
                                  temp_stats[0, columns_numeric[2]], # Assign the min value
                                  original_data_numeric[:,2])# else return the old value
original_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [130]:
temp_stats[0,columns_numeric[3]] # Mean of fourth numeric column

6.0

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [132]:
header_numeric # we are interested in the 1,3,4,5 columns(loan_amnt, int_rate, installment, total_pymnt)

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [133]:
for i in [1,3,4,5]:
    original_data_numeric[:,i] = np.where(original_data_numeric[:,i] == temp_max_fill, # if value at original_data_numeric[:,i] is same as max
                                      temp_stats[2, columns_numeric[i]], # Assign the min value 
                                      original_data_numeric[:,i])# else return the old value

In [134]:
original_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [137]:
# Import the file containing the Exchange-Rates
# We skip the first row(i.e the header) and we use column 3 only since it was the closing exchange rate
# NB* we have decimal values rounded up to 2 dp because we had set it up that way at the begining 
# The 12 exchange rates in the file are for the 12 months of the year
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD 

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [138]:
original_data_strings[:,0] # Months of the year, as we earlier filld. 0 represent null values for months

array([ 5,  0,  9, ...,  6,  4, 12])

In [141]:
exchange_rate = original_data_strings[:,0]
for i in range(1,13): # We loop through 1-12 which are the months of the year
    exchange_rate = np.where(exchange_rate == i, # if i is same as the month (i == 1 == Jan)
                             EUR_USD[i-1], # we get the value of the exchange rate 
                             exchange_rate) # else we leave the value unchange    

exchange_rate = np.where(exchange_rate == 0, # If month is null
                         np.mean(EUR_USD), # we assign the anual exchange rate to it 
                         exchange_rate)  # else we leave the value unchange 

exchange_rate    

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [142]:
exchange_rate.shape

(10000,)

In [144]:
# We need to add the exchange rate to the data set so we check the shape of the data set 
original_data_numeric.shape

(10000, 6)

In [145]:
# Shapes are different so we need to reshape the exchange_rate array
exchange_rate = np.reshape(exchange_rate, (10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [146]:
exchange_rate.shape   # Now the two arrays have the same number of rows and we can work with that

(10000, 1)

In [147]:
original_data_numeric = np.hstack((original_data_numeric, exchange_rate)) # we horrizontally stack (combine) the two array
original_data_numeric.shape # Great! Number of columns just increased by 1

(10000, 7)

In [149]:
# Swince we have added the exchange rate values to the numeric array, we also need to add it heading to the numeric header
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [151]:
header_numeric # we are trying to see the columns that contain amounts in USD, these are (1,2,4,5)

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [155]:
# We get those indices into an array so we can easily slice out the columns later and convert the amounts to EUR
columns_dollar = np.array([1,2,4,5])

In [156]:
original_data_numeric[:,[columns_dollar]] # slice out the columns that needs to be converted to EUR

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [158]:
original_data_numeric[:,6] # Exchange rate column

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [162]:
# We need to add the converted EUR amounts to the data set
# We loop through the columns_dollar containing the indices of the USD amounts to be converted into into EUR
# We convert the amount and save in a new column and then add (stack) that column to the original_data_numeric
for i in columns_dollar:
    original_data_numeric = np.hstack((original_data_numeric, np.reshape(original_data_numeric[:,i] / original_data_numeric[:,6], (10000,1))))

In [163]:
# Checking the shape of original_data_numeric we should get 4 new columns containing the converted USD to EUR amounts
original_data_numeric.shape

(10000, 11)

In [164]:
original_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

#### Expanding the header

In [167]:
# Create a new array containing the deaders to be added later using list comprehension
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [169]:
header_numeric = np.concatenate((header_numeric, header_additional)) # Adding header_additional to existing header_numeric

In [170]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR', 'loan_amnt_EUR',
       'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [172]:
# It will be better to rename(add USD) extentions to the USD amounts for clarity sowe use the same method as before 
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [173]:
header_numeric # We now have distinct USD and EUR amount columns 

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [175]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6] # We hand pick and rearrange the indices

In [179]:
# header_numeric[columns_index_order] # Test 
header_numeric = header_numeric[columns_index_order]
header_numeric

array(['id', 'loan_amnt_USD', 'installment_EUR', 'loan_amnt_EUR', 'total_pymnt_USD',
       'funded_amnt_USD', 'funded_amnt_EUR', 'total_pymnt_EUR', 'int_rate', 'exchange_rate',
       'installment_USD'], dtype='<U19')

In [181]:
original_data_numeric # tring to rearrange the value columns too

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [183]:
# original_data_numeric[:,columns_index_order] # Test
original_data_numeric = original_data_numeric[:,columns_index_order]
original_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest Rate

In [184]:
header_numeric

array(['id', 'loan_amnt_USD', 'installment_EUR', 'loan_amnt_EUR', 'total_pymnt_USD',
       'funded_amnt_USD', 'funded_amnt_EUR', 'total_pymnt_EUR', 'int_rate', 'exchange_rate',
       'installment_USD'], dtype='<U19')

In [186]:
original_data_numeric[:,5] # Interest rates are stored in percentages so we need to convert to values between 0 and 1

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [187]:
original_data_numeric[:,5] = original_data_numeric[:,5]/100 # divide all interest rate by 100 to achieve our goal

In [188]:
original_data_numeric[:,5] # We have all rates between 0 ans 1

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [189]:
# Sqve the current mile stone as we now need to move forward with combining and sorting the four arrays into 1 data set
checkpoint_numeric = checkpoint("Checkpoint-Numeric", header_numeric, original_data_numeric)

In [190]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'installment_EUR', 'loan_amnt_EUR', 'total_pymnt_USD',
        'funded_amnt_USD', 'funded_amnt_EUR', 'total_pymnt_EUR', 'int_rate', 'exchange_rate',
        'installment_USD'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [191]:
checkpoint_strings['data'].shape

(10000, 6)

In [192]:
checkpoint_numeric['data'].shape

(10000, 11)

In [196]:
# Combining the numeric and the String arrays together to form a single data set
final_loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [197]:
final_loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [198]:
np.isnan(final_loan_data).sum() # Check if the data set has some null values

0

In [200]:
# Combining the numeric and the String header arrays together to form a single header for the data set
final_loan_data_header = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))
final_loan_data_header

array(['id', 'loan_amnt_USD', 'installment_EUR', 'loan_amnt_EUR', 'total_pymnt_USD',
       'funded_amnt_USD', 'funded_amnt_EUR', 'total_pymnt_EUR', 'int_rate', 'exchange_rate',
       'installment_USD', 'issued_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'state_address'], dtype='<U19')

## Sorting the New Dataset

In [202]:
# final_loan_data[np.argsort(final_loan_data[:,0])] # Test
final_loan_data = final_loan_data[np.argsort(final_loan_data[:,0])] # We sort the data in ascending order of loan id (col 0)

In [203]:
final_loan_data # Soring works

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [204]:
np.argsort(final_loan_data[:,0]) # Verify if the data has been sorted well by checking the array indices

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

## Storing the New Dataset

In [206]:
#  np.vstack((final_loan_data_header, final_loan_data)) # Test
final_loan_data = np.vstack((final_loan_data_header, final_loan_data)) # Combine the final header and the data itself into one array

In [207]:
final_loan_data # Our complete data set looks just fine and we now have a usefull data set

array([['id', 'loan_amnt_USD', 'installment_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [208]:
# saving the the preprocessed data into a CSV file
np.savetxt("final_loan_data-preprocessed.csv", 
           final_loan_data, 
           fmt = '%s',
           delimiter = ',')